all: RDF_O RDF_TiO RDF_TiO2 RDF_Ti density energy BAD_otio BAD_tioti

energy:energy.gp
	gnuplot energy.gp

density:density.gp
	gnuplot density.gp

RDF_O:RDF_O.gp
	gnuplot RDF_O.gp

RDF_TiO:RDF_TiO.gp
	gnuplot RDF_TiO.gp

RDF_TiO2:RDF_TiO2.gp
	gnuplot RDF_TiO2.gp

RDF_Ti:RDF_Ti.gp
	gnuplot RDF_Ti.gp

BAD_otio:otio.gp
	gnuplot otio.gp

BAD_tioti:tioti.gp
	gnuplot tioti.gp

